version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
    volumes:
      - .:/app
    depends_on:
      - pinecone

  pinecone:
    image: pinecone/pinecone:latest
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}